### ISSUE TITLE
Make localeData configuration optional?

### ISSUE THREAD

**Issue by rxaviers** [devangnegandhi/globalize-express#2]
Hi,

Great library.

It would be great if [`localeData`](https://github.com/devangnegandhi/globalize-express/blob/master/example/config.js#L16-L39) was optional, so if using `cldr-data` the library automatically takes care of it, otherwise it allows users to specify a data path. Because, it might be hard for new comers to fill those values in.

I encourage considering something similar to https://github.com/rxaviers/globalize-webpack-plugin/blob/ebd0c4dd36c8610c08e636204399358602829587/util.js#L9-L11.

Thanks

**Comment by devangnegandhi** [comment]
Oh cool, sounds like a good idea. I'll incorporate this soon
